Onix/Models/SidebarViewModels.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Datos;

namespace Onix.Models
{
    public class SidebarViewModels
    {
        public IEnumerable<Categorias> Categorias { get; set; }
        public IEnumerable<SubCategorias> Subcategorias { get; set; }
        public string Cat_seleccionada { get; set; }
    }
}

Onix/Controllers/PostController.cs
using Datos;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Onix.Models;
using System.IO;
using MercadoPago;
using MercadoPago.Resources;
using Newtonsoft.Json;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using System.Threading.Tasks;
using CloudinaryDotNet;
using CloudinaryDotNet.Actions;
using System.Net.PeerToPeer;
using System.Net;
using ObjectDumper;
using System.Drawing;
using System.Drawing.Imaging;
using System.Security.Principal;

namespace Onix.Controllers
{
    public class PostController : Controller
    {
        private onixDBEntities db = new onixDBEntities();
        private static List<ImagenViewModels> listaImagenesPosts = new List<ImagenViewModels>();
        private static List<ImagenViewModels> listaImagenesCanjes = new List<ImagenViewModels>();
        private static string IdImagen = "";
        private static string pathOpt = "";
        private static byte[] ImagenDestacada = null;
        private static string TituloAviso = null;

        // GET: Post
        public ActionResult Index(int id)
        {
            try
            {
                //recupero img guardadas por un canje anterior no confirmado
                List<string> files_routes = new List<string>();
                if (listaImagenesCanjes.Count() > 0)
                {
                    foreach (var item in listaImagenesCanjes)
                    {
                        files_routes.Add(item.Nombre);
                    }
                    ViewBag.FilesRoute = files_routes;
                }

                List<Imagenes> listaImg = new List<Imagenes>();
                List<Comentarios> listaComUsuarios = new List<Comentarios>();
                listaComUsuarios = db.Comentarios.Where(x => x.IdPost == id && x.IdEstado == 1).ToList();
                var post = db.Posts.Where(x => x.Id == id && x.IdEstado == 1).First();
                PostViewModels model = new PostViewModels();
                model.IdPost = post.Id;
                model.IdUsuario = post.IdUsuario;
                model.ApellidoUsuario = post.ApellidoUsuario;
                model.Celular = post.Celular;
                model.Descripcion = post.Descripcion;
                listaImg = db.Imagenes.Where(x => x.IdPost == id).ToList();
                foreach (var item in listaImg)
                {
                    model.ListaImagenes.Add(item.imagen);
                }
                model.Direccion = post.Direccion;
                model.Email = post.Email;
                model.Fecha = post.FechaPublicacion;
                model.Localidad = post.Localidad;
                model.LocalidadContacto = post.LocalidadContacto;
                model.Moneda = post.Moneda;
                model.NombreUsuario = post.NombreUsuario;
                model.PermiteCanjes = post.PermiteCanjes;
                model.PermiteContraofertas = post.PermiteContraofertas;
                model.PermiteCuotas = post.PermiteCuotas;
                model.PermitePreguntas = post.PermitePreguntas;
                model.Precio = post.Precio;
                model.TelefonoFijo = post.TelefonoFijo;
                model.Titulo = post.Titulo;
                model.Visitas = post.Visitas;
                model.Categoria = db.Categorias.Where(x => x.Id == post.IdCategoria).First().Descripcion;
                model.SubCategoria = db.SubCategorias.Where(x => x.Id == post.IdSubCategoria).First().Descripcion;
                model.ApellidoVisible = (bool)post.ApellidoUsuarioVisible;
                model.EmailVisible = (bool)post.EmailVisible;
                model.CelularVisible = (bool)post.CelularVisible;
                model.TelefonoVisible = (bool)post.TelefonoFijoVisible;
                model.DomicilioVisible = (bool)post.DireccionVisible;
                model.LocalidadVisible = (bool)post.LocalidadContactoVisible;
                model.CantidadPublicaciones = db.Posts.Where(x => x.IdUsuario == post.IdUsuario && x.IdEstado == 1).Count();
                model.Prioridad = post.Prioridad;
                List<Votos> votosRecibidosUsu = db.Votos.Where(x => x.IdUsuarioDestino == post.IdUsuario).ToList();
                if (votosRecibidosUsu.Count() > 0)
                {
                    int votosPositivosUsu = votosRecibidosUsu.Where(x => x.VotoPositivo == true).Count();
                    decimal valoracionesPositivas = (votosPositivosUsu * 100) / votosRecibidosUsu.Count();
                    model.ValoracionesPositivas = Convert.ToInt32(valoracionesPositivas);
                }
                else
                {
                    model.ValoracionesPositivas = -1;
                }
                switch (model.Categoria)
                {
                    case "Automotores":
                        model.Automotores = db.CaracteristicasAutomotores.Where(x => x.IdPost == id).First();
                        break;
                    case "Agro":
                        model.Agro = db.CaracteristicasAgro.Where(x => x.IdPost == id).First();
                        break;
                    case "Animales":
                        model.Animales = db.CaracteristicasAnimales.Where(x => x.IdPost == id).First();
                        break;
                    case "Bebes y Niños":
                        model.BebesNinos = db.CaracteristicasBebesNinos.Where(x => x.IdPost == id).First();
                        break;
                    case "Electrónica":
                        model.Electronica = db.CaracteristicasElectronica.Where(x => x.IdPost == id).First();
                        break;
                    case "Empleos":
                        model.Empleos = db.CaracteristicasEmpleos.Where(x => x.IdPost == id).First();
                        break;
                    case "Hogar y Muebles":
                        model.HogarMuebles = db.CaracteristicasHogarMuebles.Where(x => x.IdPost == id).First();
                        break;
                    case "Inmuebles":
                        model.Inmuebles = db.CaracteristicasInmuebles.Where(x => x.IdPost == id).First();
                        break;
                    case "Varios":
                        model.Varios = db.CaracteristicasVarios.Where(x => x.IdPost == id).First();
                        break;
                    default:
                        break;
                }
                AspNetUsers usuario = new AspNetUsers();
                usuario = db.AspNetUsers.Where(x => x.Id == post.IdUsuario).FirstOrDefault();
                ImagenesUsuarios imgUsuarioPost = db.ImagenesUsuarios.Where(x => x.IdUsuario == usuario.Id).FirstOrDefault();
                if (imgUsuarioPost != null)
                {
                    model.ImagenUsuario = imgUsuarioPost.imagen;
                }
                else
                {
                    model.ImagenUsuario = null;
                }
                List<ImagenesUsuarios> ListaImgUsuarios = db.ImagenesUsuarios.ToList();
                List<ComentarioViewModels> comentarios = new List<ComentarioViewModels>();
                foreach (var com in listaComUsuarios)
                {
                    bool tiene_imagen = false;
                    foreach (var imgusu in ListaImgUsuarios)
                    {
                        if (com.IdUsuario == imgusu.IdUsuario)
                        {
                            tiene_imagen = true;
                            comentarios.Add(new ComentarioViewModels
                            {
                                Imagen = imgusu.imagen,
                                Nombre = com.AspNetUsers.Nombre,
                                Contenido = com.Contenido,
                                Fecha = com.Fecha,
                                EsVendedor = com.IdUsuario == model.IdUsuario ? true : false
                            });
                            break;
                        }
                    }
                    if (!tiene_imagen)
                    {
                        comentarios.Add(new ComentarioViewModels
                        {
                            Imagen = null,
                            Nombre = com.AspNetUsers.Nombre,
                            Contenido = com.Contenido,
                            Fecha = com.Fecha,
                            EsVendedor = com.IdUsuario == model.IdUsuario ? true : false
                        });
                    }
                }
                model.ListaComentarios = comentarios;
                List<Contraofertas> ListaContraofertas = new List<Contraofertas>();
                ListaContraofertas = db.Contraofertas.Where(x => x.IdPost == post.Id && x.EstadoContraoferta == "Activa").ToList();
                List<Canjes> ListaCanjes = new List<Canjes>();
                ListaCanjes = db.Canjes.Where(x => x.IdPost == post.Id && x.EstadoCanje == "Activo").ToList();

                foreach (var contraoferta in ListaContraofertas)
                {
                    ContraOfertasViewModels ofertaModel = new ContraOfertasViewModels();
                    ofertaModel.Id = contraoferta.Id;
                    ofertaModel.IdPost = contraoferta.IdPost;
                    AspNetUsers persona = new AspNetUsers();
                    persona = db.AspNetUsers.Where(x => x.Id == contraoferta.IdUsuario).FirstOrDefault();
                    ofertaModel.IdUsuario = persona.Id;
                    ofertaModel.NombreUsuario = persona.Nombre;
                    ofertaModel.ApellidoUsuario = persona.Apellido;
                    ofertaModel.Precio = contraoferta.Precio;
                    model.ListaContraOfertas.Add(ofertaModel);
                }
                foreach (var canje in ListaCanjes)
                {
                    CanjesViewModels canjeModel = new CanjesViewModels();
                    canjeModel.Id = canje.Id;

Onix/Views/Shared/_CaracteristicasProducto.cshtml
<h5>Características del producto</h5>
<span class="form-icon-wrapper">
    <a class="text-center d-block" data-toggle="tooltip" data-placement="top" title="" data-original-title="Incluye estado, características y detalles que consideres relevantes">
        <form>
            <div class="form-group">
                <textarea id="comentario" class="form-control" rows="6"></textarea>
            </div>
        </form>
    </a>
</span>

Onix/Views/Shared/_FileUpload.cshtml
<div class="panel panel-default">
    <div class="panel-body">

        @using (Html.BeginForm("UploadFile", "Imagen", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            <div class="form-inline">
                <div class="form-group">
                    <input type="file" name="file" multiple>
                </div>
                <button type="submit" class="btn btn-sm btn-primary">Subir fotos</button>
            </div>
        }

        @*<form action="" method="post" enctype="multipart/form-data" id="js-upload-form" style="margin-bottom:6px;">
            <div class="form-inline">
                <div class="form-group">
                    <input type="file" name="files[]" id="js-upload-files" multiple>
                </div>
                <button type="submit" class="btn btn-sm btn-primary" id="js-upload-submit">Subir fotos</button>
            </div>
        </form>*@

        <!-- Drop Zone -->
        <div class="upload-drop-zone" id="drop-zone">
            También podés arrastrar tus fotos acá
        </div>

        @{
            if (ViewBag.UploadSuccess == true)
            {
                <!-- Upload Finished -->
                <div class="js-upload-finished">
                    <h6>Archivos procesados</h6>
                    <div class="list-group">
                        <a href="#" class="list-group-item list-group-item-success"><span class="badge alert-success pull-right">Success</span>ViewBag.FileName</a>
                    </div>
                </div>
            }
        }

        <!-- Progress Bar -->
        <div class="progress">
            <div class="progress-bar" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 60%;">
                <span class="sr-only">60% Complete</span>
            </div>
        </div>
    </div>
</div>

Onix/Views/Shared/_Footer.cshtml
<footer>
    <div class="container">
        <div class="row">
            <div class="col-md-8 text-center text-md-left mb-3 mb-md-0">
                <small class="text-white">
                    ® Copyright onixbusiness.com © @DateTime.Now.Year

                    Rafaela.

                    Todos los derechos reservados.
                </small>
            </div>

            <div class="col-md-4 align-self-center">
                <ul class="list-inline text-center text-md-right mb-0">
                    <li class="list-inline-item mx-2" data-toggle="tooltip" data-placement="top" title="" data-original-title="Facebook">
                        <a class="text-white" target="_blank" href="https://www.facebook.com/onixlatam">
                            <i class="fab fa-facebook"></i>
                        </a>
                    </li>
                    <li class="list-inline-item mx-2" data-toggle="tooltip" data-placement="top" title="" data-original-title="Instagram">
                        <a class="text-white" target="_blank" href="https://www.instagram.com/onixbusiness.arg/">
                            <i class="fab fa-instagram"></i>
                        </a>
                    </li>
                    <li class="list-inline-item mx-2" data-toggle="tooltip" data-placement="top" title="" data-original-title="Twitter">
                        <a class="text-white" target="_blank" href="https://twitter.com/">
                            <i class="fab fa-twitter"></i>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</footer>

Onix/Views/Shared/_HighLight.cshtml
<div class="single category" style="padding: 12px; border:solid 0.25rem #59287a; background:linear-gradient(to bottom, #ce4040 8%,white 12%); box-shadow:0 2px 5px 0 rgba(0, 0, 0, 0.16), 0 2px 10px 0 rgba(0, 0, 0, 0.4);">
    <h4 style="font-weight:bold; margin-bottom:3px; color:white; text-align:center;">DESTACÁ TU AVISO</h4>
    <hr style="border-color:#59287a; border:none; height:3px; background-color:#59287a;" />
    @*TO DO: Cargar datos del post que se esta destacando*@
    @*<a class="white-panel" href="@Url.Action("Index", "Post", new { id = ViewBag.Posts[i].idPost})">
            <div class="imagen-panel">
                <img class="imagen-tarjeta" src="data:image;base64,@System.Convert.ToBase64String(ViewBag.Posts[i].Imagen)" alt="">
            </div>
            <p class="subtitulo-tarjeta">@ViewBag.Posts[i].Descripcion</p>
        </a>
        <hr style="border-color:#59287a; border:none; height:3px; background-color:#59287a;" />
    *@
    <h5 style="text-align:left"><b>Período premium</b></h5>
    <hr style="border-color:#59287a; margin-top:0px;" />
    <div class="row">
        <div class="col-sm-4 col-lg-4">
            <div class="custom-control custom-radio mb-2">
                <input type="radio" class="custom-control-input" name="destacar-aviso-dias" id="radio-4-dias" value="radio-4-dias" checked>
                <label class="custom-control-label u-font-size-90" for="radio-4-dias">Premium por 4 días</label>
            </div>
        </div>
        <div class="col-sm-4 col-lg-4">
            <div class="custom-control custom-radio mb-2">
                <input type="radio" class="custom-control-input" name="destacar-aviso-dias" id="radio-8-dias" value="radio-8-dias">
                <label class="custom-control-label u-font-size-90" for="radio-8-dias">Premium por 8 días</label>
            </div>
        </div>
    </div>
    <h5 style="text-align:left"><b>Tipo premium</b></h5>
    <hr style="border-color:#59287a; margin-top:0px;" />
    <div class="row">
        <div class="col-sm-4 col-lg-4">
            <div class="custom-control custom-radio mb-2">
                <input type="radio" class="custom-control-input" name="destacar-aviso-tipo" id="radio-estandar" value="radio-estandar" checked>
                <label class="custom-control-label u-font-size-90" for="radio-estandar">Premium Estándar <b>($125)</b></label>
            </div>
        </div>
        <div class="col-sm-4 col-lg-4">
            <div class="custom-control custom-radio mb-2">
                <input type="radio" class="custom-control-input" name="destacar-aviso-tipo" id="radio-avanzado" value="radio-avanzado">
                <label class="custom-control-label u-font-size-90" for="radio-avanzado">Premium Avanzado <b>($210)</b></label>
            </div>
        </div>
        <div class="col-sm-4 col-lg-4">
            <div class="custom-control custom-radio mb-2">
                <input type="radio" class="custom-control-input" name="destacar-aviso-tipo" id="radio-destacado" value="radio-destacado">
                <label class="custom-control-label u-font-size-90" for="radio-destacado">Premium Destacado <b>($295)</b></label>
            </div>
        </div>
    </div>
    <hr style="border-color:#59287a; border:none; height:3px; background-color:#59287a;" />
    <h5 style="font-weight:bold; margin-bottom:8px; color:black; text-align:center;">Previsualización de tu aviso</h5>
    <section id="pinBoot" style="position: relative; left:38%">
        <a class="white-panel" href="" style="text-align:center; background:linear-gradient(to bottom, #ce4040 10%,white 50%);">
            <div class="imagen-panel">
                <span class="banda-destacado">15%</span>
                <img class="imagen-tarjeta" src="@Url.Content("~/Content/img/perfil_prueba.jpg")" alt="">
            </div>
            <p class="subtitulo-tarjeta">Descripcion del articulo</p>
        </a>
    </section>
    <div class="row">
        <div class="col-sm-12 col-lg-12" style="padding:0px; text-align:center;">
            <div style="padding:0px;">
                @*BOTONES DE PAGO MERCADOPAGO*@
                <div id="btn-destacar-4-estandar">
                    <a mp-mode="dftl" href="https://www.mercadopago.com.ar/checkout/v1/redirect?pref_id=163942691-cab71d6d-e3c4-4272-88f1-6ef1107149e6" name="MP-payButton" class='blue-ar-l-rn-aron'>Pagar con MercadoPago</a>
                    <script type="text/javascript">
                        (function () { function $MPC_load() { window.$MPC_loaded !== true && (function () { var s = document.createElement("script"); s.type = "text/javascript"; s.async = true; s.src = document.location.protocol + "//secure.mlstatic.com/mptools/render.js"; var x = document.getElementsByTagName('script')[0]; x.parentNode.insertBefore(s, x); window.$MPC_loaded = true; })(); } window.$MPC_loaded !== true ? (window.attachEvent ? window.attachEvent('onload', $MPC_load) : window.addEventListener('load', $MPC_load, false)) : null; })();
                    </script>
                </div>

                <div id="btn-destacar-4-avanzado" style="display:none">
                    <a mp-mode="dftl" href="https://www.mercadopago.com.ar/checkout/v1/redirect?pref_id=163942691-3005a032-f4cf-4217-9843-9e4f9767cc2e" name="MP-payButton" class='blue-ar-l-rn-aron'>Pagar con MercadoPago</a>
                    <script type="text/javascript">
                        (function () { function $MPC_load() { window.$MPC_loaded !== true && (function () { var s = document.createElement("script"); s.type = "text/javascript"; s.async = true; s.src = document.location.protocol + "//secure.mlstatic.com/mptools/render.js"; var x = document.getElementsByTagName('script')[0]; x.parentNode.insertBefore(s, x); window.$MPC_loaded = true; })(); } window.$MPC_loaded !== true ? (window.attachEvent ? window.attachEvent('onload', $MPC_load) : window.addEventListener('load', $MPC_load, false)) : null; })();
                    </script>
                </div>

                <div id="btn-destacar-4-destacado" style="display:none">
                    <a mp-mode="dftl" href="https://www.mercadopago.com.ar/checkout/v1/redirect?pref_id=163942691-e93aa68a-380d-4b78-a959-cc5661a9bb1a" name="MP-payButton" class='blue-ar-l-rn-aron'>Pagar con MercadoPago</a>
                    <script type="text/javascript">
                        (function () { function $MPC_load() { window.$MPC_loaded !== true && (function () { var s = document.createElement("script"); s.type = "text/javascript"; s.async = true; s.src = document.location.protocol + "//secure.mlstatic.com/mptools/render.js"; var x = document.getElementsByTagName('script')[0]; x.parentNode.insertBefore(s, x); window.$MPC_loaded = true; })(); } window.$MPC_loaded !== true ? (window.attachEvent ? window.attachEvent('onload', $MPC_load) : window.addEventListener('load', $MPC_load, false)) : null; })();
                    </script>
                </div>

                <div id="btn-destacar-8-estandar" style="display:none">
                    <a mp-mode="dftl" href="https://www.mercadopago.com.ar/checkout/v1/redirect?pref_id=163942691-58409d30-2a45-44de-887b-0ed9af531f19" name="MP-payButton" class='blue-ar-l-rn-aron'>Pagar con MercadoPago</a>
                    <script type="text/javascript">
                        (function () { function $MPC_load() { window.$MPC_loaded !== true && (function () { var s = document.createElement("script"); s.type = "text/javascript"; s.async = true; s.src = document.location.protocol + "//secure.mlstatic.com/mptools/render.js"; var x = document.getElementsByTagName('script')[0]; x.parentNode.insertBefore(s, x); window.$MPC_loaded = true; })(); } window.$MPC_loaded !== true ? (window.attachEvent ? window.attachEvent('onload', $MPC_load) : window.addEventListener('load', $MPC_load, false)) : null; })();
                    </script>
                </div>

                <div id="btn-destacar-8-avanzado" style="display:none">
                    <a mp-mode="dftl" href="https://www.mercadopago.com.ar/checkout/v1/redirect?pref_id=163942691-980108d2-f4fe-41c3-a42a-a0448fa349d6" name="MP-payButton" class='blue-ar-l-rn-aron'>Pagar con MercadoPago</a>
                    <script type="text/javascript">
                        (function () { function $MPC_load() { window.$MPC_loaded !== true && (function () { var s = document.createElement("script"); s.type = "text/javascript"; s.async = true; s.src = document.location.protocol + "//secure.mlstatic.com/mptools/render.js"; var x = document.getElementsByTagName('script')[0]; x.parentNode.insertBefore(s, x); window.$MPC_loaded = true; })(); } window.$MPC_loaded !== true ? (window.attachEvent ? window.attachEvent('onload', $MPC_load) : window.addEventListener('load', $MPC_load, false)) : null; })();
                    </script>
                </div>

                <div id="btn-destacar-8-destacado" style="display:none">
                    <a mp-mode="dftl" href="https://www.mercadopago.com.ar/checkout/v1/redirect?pref_id=163942691-47699ac1-6421-4ba8-9327-8d020bb5d353" name="MP-payButton" class='blue-ar-l-rn-aron'>Pagar con MercadoPago</a>
                    <script type="text/javascript">
                        (function () { function $MPC_load() { window.$MPC_loaded !== true && (function () { var s = document.createElement("script"); s.type = "text/javascript"; s.async = true; s.src = document.location.protocol + "//secure.mlstatic.com/mptools/render.js"; var x = document.getElementsByTagName('script')[0]; x.parentNode.insertBefore(s, x); window.$MPC_loaded = true; })(); } window.$MPC_loaded !== true ? (window.attachEvent ? window.attachEvent('onload', $MPC_load) : window.addEventListener('load', $MPC_load, false)) : null; })();
                    </script>
                </div>
            </div>
        </div>
    </div>
</div>
@Scripts.Render("~/Content/vendor/jquery/jquery.min.js")
<script type="text/javascript">
    $(document).ready(function () {
        //var alertAvisoPublicado = document.getElementById("avisoPublicado").style.display = "none"; USAR PARA DESTACAR AVISO CORRECTO
        var boton_a_ocultar = "#btn-destacar-4-estandar";
        $('.custom-control-input').change(function () { //cuando cualquiera de los radios cambia, obtengo el valor de los checked
            switch ($("input[name='destacar-aviso-dias']:checked").val()) {
                case 'radio-4-dias':
                    switch ($("input[name='destacar-aviso-tipo']:checked").val()) {
                        case 'radio-estandar':
                            $(boton_a_ocultar).hide();
                            $("#btn-destacar-4-estandar").show();
                            boton_a_ocultar = $("#btn-destacar-4-estandar");
                            break;
                        case 'radio-avanzado':
                            $(boton_a_ocultar).hide();
                            $("#btn-destacar-4-avanzado").show();
                            boton_a_ocultar = $("#btn-destacar-4-avanzado");
                            break;
                        case 'radio-destacado':
                            $(boton_a_ocultar).hide();
                            $("#btn-destacar-4-destacado").show();
                            boton_a_ocultar = $("#btn-destacar-4-destacado");
                            break;
                    }
                    break;
                case 'radio-8-dias':
                    switch ($("input[name='destacar-aviso-tipo']:checked").val()) {
                        case 'radio-estandar':
                            $(boton_a_ocultar).hide();
                            $("#btn-destacar-8-estandar").show();
                            boton_a_ocultar = $("#btn-destacar-8-estandar");
                            break;
                        case 'radio-avanzado':
                            $(boton_a_ocultar).hide();
                            $("#btn-destacar-8-avanzado").show();
                            boton_a_ocultar = $("#btn-destacar-8-avanzado");
                            break;
                        case 'radio-destacado':
                            $(boton_a_ocultar).hide();
                            $("#btn-destacar-8-destacado").show();
                            boton_a_ocultar = $("#btn-destacar-8-destacado");
                            break;
                    }
                    break;
            }
        });
    });
    $(document).on("click", "input[name=radio-4-dias]:radio", function () {
        $("input[name=radio-8-dias]:radio").prop('checked', false);
    });
    $(document).on("click", "input[name=radio-8-dias]:radio", function () {
        $("input[name=radio-4-dias]:radio").prop('checked', false);
    });
    $(document).on("click", "input[name=radio-estandar]:radio", function () {
        $("input[name=radio-avanzado]:radio").prop('checked', false);
        $("input[name=radio-destacado]:radio").prop('checked', false);
    });
    $(document).on("click", "input[name=radio-avanzado]:radio", function () {
        $("input[name=radio-estandar]:radio").prop('checked', false);
        $("input[name=radio-destacado]:radio").prop('checked', false);
    });
    $(document).on("click", "input[name=radio-destacado]:radio", function () {
        $("input[name=radio-estandar]:radio").prop('checked', false);
        $("input[name=radio-avanzado]:radio").prop('checked', false);
    });

    // NO FUNCIONA EL Z INDEX DE LA BARRA DE NAV
    // ME TOMA SIEMPRE EL BOTON 8 DIAS ESTANDAR

</script>

@*CHECKOUT MERCADOPAGO*@
@*<form action="@Url.Action("Destacar","Post")" method="POST" enctype="multipart/form-data">
        <script src="https://www.mercadopago.com.ar/integrations/v1/web-payment-checkout.js"
                data-preference-id="@Html.DisplayFor(model => model.Id)">
        </script>
    </form>*@

Onix/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="onixbusiness es un sitio web de compra y venta en la ciudad de Rafaela, Santa Fe, Argentina. Comprá y vendé lo que querés." />
    <title>ONIX | Comprá y vendé lo que querés en Rafaela</title>
    @Styles.Render("~/bundles/css")
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
    <link rel="stylesheet" href="~/Content/css/sweetalert2.min.css">

</head>
<body class="bg-gradient-primary">
    @RenderBody()


    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <script src="https://cdn.jsdelivr.net/gh/mathusummut/confetti.js/confetti.min.js"></script>
    <script src="~/Content/js/sweetalert2.all.min.js"></script>
</body>
</html>